org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.20
forge_version_range=[47.4.20,48)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

mod_id=projectjapan
mod_name=Project Japan
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=com.sora.projectjapan
mod_authors=Sora
mod_description=Project Japan at X:Y:Z scale 0.125:0.25:0.125 with 115 frozen authored rivers, final river/lake geometry, final-ground surface painting and material-aware vegetation for Minecraft Forge 1.20.1.
